version: '3.8'

networks:
  project-management-service:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: management-db
    environment:
      POSTGRES_DB: management-db
      POSTGRES_USER: management-user
      POSTGRES_PASSWORD: password
    env_file:
      - app.env
    ports:
      - "5432:5432"
    networks: 
      - project-management-service

  app:
    image: management-list
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-service
    environment:
      DB_SOURCE: postgresql://management-user:password@db:5432/management-db?sslmode=disable
      PORT: 8080
    env_file:
      - app.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - project-management-service
